version: '3.8'

services:
  fuse_translation:
    image: godver3/fuse_translate:latest
    ports:
      - "${PORT:-6000}:6000"
    volumes:
      - /path/to/translated/mnt:/mnt/translated:rshared
      - /path/to/original/mnt:/mnt/original
      - /path/to/database:/app/database
      - /path/to/database/backups:/app/backups
      - /path/to/logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    command: python main.py /mnt/translated /mnt/original database/translations.db backups
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    restart: always
